# Generated by Django 5.1.6 on 2025-03-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_response_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="question",
        ),
        migrations.RemoveField(
            model_name="response",
            name="user",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
