# Generated by Django 5.1.7 on 2025-03-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_response_question_remove_response_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
